swagger: "2.0"
info:
  description: "This represents API spec for Pricing Service."
  version: "1.0.0"
  title: "Pricing Service APIs"
  contact:
    email: "raghu@xyz.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
tags:
- name: "Pricing Service"
  description: "Provides APIs to fetch Pricing of a given Course."
- name: "Health Check"
  description: "Provides API to check Health of Pricing Service."
schemes:
- "http"
paths:
  /lms/v1/price/course/{courseId}:
    get:
      tags:
      - "Pricing Service"
      summary: "Find Pricing by Course ID"
      description: "Returns a Pricing Details"
      operationId: "getPriceByCoursId"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "ID of Course for which Pricing return"
        required: true
        type: "integer"
        format: "int64"
      - name: "inline"
        in: "query"
        description: "True if need detailed pricing else false"
        required: false
        type: "boolean"
      - name: "currency"
        in: header
        description: "What kind of Pricing is Requested. E.g. INR / USD"
        required: true
        type: "string"
        enum:
          - "INR"
          - "USD"
      responses:
        200:
          description: "Successfull Retrieval"
          schema:
            $ref: "#/definitions/CoursePricingResponse"
        400:
          description: "Invalid Request."
          schema:
            $ref: "#/definitions/ErrorResponse"
        404:
          description: "Course not found"
          schema:
            $ref: "#/definitions/ErrorResponse"
  '/actuator/health':
    get:
      tags:
      - "Pricing Service"
      operationId: Detailed health check of current service
      summary: Detailed health check of current service
      responses:
        200:
          description: Details of each component service is communicating.
          schema:
            $ref: '#/definitions/detailed-health-response'
        400:
          description: "Invalid Request."
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  CoursePricingResponse:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/PricingResponse"
  PricingResponse:
    type: "object"
    properties:
      salePrice:
        type: "number"
        example: 600.99
      price:
        type: "number"
        example: 500.99
      totalPrice:
        type: "number"
        example: 551.99
      totalTax:
        type: "number"
        example: 51.99
      subscriptionName:
        type: "string"
        example: "6 Month"
      subscriptionId:
        type: "number"
        example: 4
      taxes:
        type: "array"
        items:
          $ref: "#/definitions/Tax"
      currency:
        type: "string"
        description: "Currency of Pricing Response"
        enum:
        - "INR"
        - "USD"
  Tax:
    type: "object"
    properties:
      percentage:
        type: "number"
        example: 10.99
      taxAmount:
        type: "number"
        example: 51.99
      label:
        type: "string"
        example: "GST"
      fixedTaxAmount:
        type: "number"
        example: 0.00
  ErrorResponse:
    type: "object"
    properties:
      errorCFode:
        type: "integer"
        format: "int64"
      errorMessage:
        type: "string"
  detailed-health-response:
      description: detailed health check of each internal components.
      type: object
      properties:
        status:
          type: string
          example: "UP"
        components:
          type: object
          properties:
            db:
              type: object
              properties:
                status:
                  type: string
                  example: UP
